version: "2"
run:
  go: "1.25"
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
  settings:
    staticcheck:
      checks:
        - all
        - -QF1008 # ignore omit embbed fields from selector expressions
        - -ST1000 # Incorrect or missing package comment
        - -ST1003 # Poorly chosen identifier
        - -ST1005 # Incorrectly formatted error string
        - -ST1006 # Poorly chosen receiver name
        - -ST1012 # Poorly chosen name for error variable
        - -ST1016 # Use consistent method receiver names
        - -SA1019 # Using a deprecated function, variable, constant or field
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - ineffassign
        path: conversion\.go
    paths:
      - ^zz_generated.*
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
