name: 'Tag Release'

on:
  push:
    branches:
      - master
      - 'release-*'
    paths:
      - kops-version.go

jobs:
  tag-release:
    if: ${{ github.repository == 'kubernetes/kops' }}
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - run: /usr/bin/git config --global user.email actions@github.com
      - run: /usr/bin/git config --global user.name 'GitHub Actions Release Tagger'
      - run: hack/tag-release.sh
